# Cross-Validation Configuration
# Configuration for cross-validation experiments

# Data settings
data:
  hormone_data_path: "outputs/data/full_hormone_data_labeled.csv"
  survey_data_path: "outputs/data/survey_responses.csv"
  period_data_path: "outputs/data/period_sleep_data.csv"
  test_size: 0.2
  random_state: 42
  n_samples_per_subject: 7

# Prior testing configuration
prior_testing:
  enabled: true  # Set to false to run only pure ML cross-validation
  test_both: true  # Set to true to run both ML-only and ML+prior evaluations
  prior_weight: 0.3  # Weight for prior in combined predictions

# Feature engineering
features:
  hormone_features: ["estradiol", "progesterone", "testosterone"]
  normalize_features: true
  add_interaction_features: true
  add_ratio_features: true

# Model parameters
models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42

  logistic_regression:
    C: 0.1
    max_iter: 1000
    random_state: 42

  support_vector_machine:
    C: 1.0
    kernel: "rbf"
    gamma: "scale"
    random_state: 42

  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

  lightgbm:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Cross-validation settings
cross_validation:
  cv_folds: 5
  cv_repeats: 3
  test_size: 0.2
  random_state: 42
  stratified: true
  scoring: "accuracy"

# Model evaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  scoring: "accuracy"
  n_jobs: -1

# Data splitting
data_splitting:
  group_by: "subject_id"  # Group by subject to avoid data leakage
  shuffle: true
  random_state: 42

# Output settings
output:
  results_dir: "outputs/reports"
  figures_dir: "outputs/figures"
  save_cv_results: true
  save_best_model: true
  generate_learning_curves: true
  generate_validation_curves: true 