# Simulation Configuration
# Configuration for hormone and period data simulation

# General simulation parameters
simulation:
  n_subjects: 100
  n_hormone_samples: 70
  n_period_days: 150
  random_seed: 22

# Phase durations (days) from https://osf.io/preprints/psyarxiv/kzvce_v1 (Doornweerd et al. 2025)
# Original proportions maintained but scaled to achieve subject's reported cycle_length
phase_durations:
  perimenstruation:
    mean: 3.6
    sd: 1.2
  mid_follicular:
    mean: 10.1
    sd: 2.7
  periovulation:
    mean: 4.2
    sd: 1.4
  early_luteal:
    mean: 5.7
    sd: 3.1
  mid_late_luteal:
    mean: 11.1
    sd: 5.3

# Cycle length distribution (days) from https://osf.io/preprints/psyarxiv/kzvce_v1 (Doornweerd et al. 2025)
cycle_length:
  mean: 28.3
  sd: 2.5
  min: 24
  max: 36

# Hormone distributions for simulation
# Values (pg/ml) from https://www.sciencedirect.com/science/article/pii/S0018506X23001198#f0020 (Gloe et al. 2023)
hormones:
  estradiol:
    perimenstruation:
      min: 0.28
      max: 2.64
      mean: 1.28
      sd: 0.54
    mid_follicular:
      min: 0.28
      max: 2.64
      mean: 1.28
      sd: 0.54
    periovulation:
      min: 0.48
      max: 4.3
      mean: 2.0
      sd: 0.76
    early_luteal:
      min: 0.3
      max: 3.14
      mean: 1.59
      sd: 0.6
    mid_late_luteal:
      min: 0.3
      max: 2.63
      mean: 1.27
      sd: 0.57
  
  progesterone:
    perimenstruation:
      min: 32.9
      max: 312.53
      mean: 119.96
      sd: 66.45
    mid_follicular:
      min: 32.9
      max: 312.53
      mean: 119.96
      sd: 66.45
    periovulation:
      min: 21.96
      max: 351.74
      mean: 149.78
      sd: 85.98
    early_luteal:
      min: 63.35
      max: 651.50
      mean: 283.01
      sd: 129.34
    mid_late_luteal:
      min: 15.76
      max: 386.08
      mean: 153.19
      sd: 88.5
  
  testosterone:
    perimenstruation:
      min: 126.7
      max: 146.5
      mean: 136.57
      sd: 78.0
    mid_follicular:
      min: 126.7
      max: 146.5
      mean: 136.57
      sd: 78.0
    periovulation:
      min: 126.7
      max: 146.5
      mean: 136.57
      sd: 78.0
    early_luteal:
      min: 126.7
      max: 146.5
      mean: 136.57
      sd: 78.0
    mid_late_luteal:
      min: 126.7
      max: 146.5
      mean: 136.57
      sd: 78.0

# Output settings
output:
  data_dir: "outputs/data"
  figures_dir: "outputs/figures"
  reports_dir: "outputs/reports"
  save_hormone_data: true
  save_period_data: true
  save_patterns: true
  save_survey_data: true
  plot_hormone_cycles: true
  n_plot_subjects: 5 