# Training Configuration
# Configuration for training menstrual pattern classification models

# Data settings
data:
  labeled_data_path: "outputs/data/full_hormone_data_labeled.csv"
  period_data_path: "outputs/data/period_sleep_data.csv"
  survey_data_path: "outputs/data/survey_responses.csv"
  test_size: 0.2
  random_state: 42

# Feature engineering
features:
  hormone_features: ["estradiol", "progesterone", "testosterone"]
  normalize_features: true
  add_interaction_features: true
  add_ratio_features: true

# Model parameters
models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
  
  logistic_regression:
    C: 10.0
    max_iter: 500
    solver: "lbfgs"
    tol: 0.000001
    random_state: 42
  
  support_vector_machine:
    C: 1.0
    kernel: "rbf"
    gamma: "scale"
    random_state: 42
  
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
  
  lightgbm:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
  
  temporal:
    sequence_length: 70
    use_as_prior: false
    prior_weight: 0.3

# Cross-validation
cross_validation:
  cv_folds: 5
  scoring: "accuracy"
  n_jobs: -1

# Output settings
output:
  models_dir: "outputs/models"
  results_dir: "outputs/reports"
  figures_dir: "outputs/figures"
  save_model: true
  save_predictions: true
  generate_confusion_matrix: true
  generate_feature_importance: true
  save_training_metrics: true 